# Generated by Django 4.2.7 on 2023-12-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_grade_enrollment_year_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_name',
        ),
    ]
