# Generated by Django 4.2.7 on 2023-12-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_department_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
