# Generated by Django 4.2.7 on 2024-01-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
    ]
