# Generated by Django 4.2.7 on 2024-01-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_student_course_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
