# Generated by Django 4.2.7 on 2024-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_student_age_alter_enrollment_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
