# Generated by Django 4.2.7 on 2024-01-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
